#!/bin/bash
clear
CONFIG="/usr/local/etc/xray/config.json"
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${ORANGE}         RENEW HYSTERIA2 ACCOUNT          ${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

if [[ $(grep -c "// #hy " "$CONFIG") == '0' ]]; then
    echo -e "${RED}Error: No Hysteria2 clients found!${NC}"
    exit 1
fi

echo -e " NO   USER          EXPIRES"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
grep -E "// #hy " "$CONFIG" | awk '{print $3, $4}' | sort | uniq | awk '{printf " %-4s %-13s %-10s\n", NR".", $1, $2}'
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

read -p " Select Number : " num
user=$(grep -E "// #hy " "$CONFIG" | awk '{print $3}' | sort | uniq | sed -n "${num}p")
exp=$(grep -E "// #hy " "$CONFIG" | grep "$user" | awk '{print $4}' | head -n 1)

if [[ -z "$user" ]]; then
    echo -e "${RED}Error: Invalid selection.${NC}"
    exit 1
fi

read -p " Add Days      : " days
[[ -z "$days" ]] && days=30

now=$(date +%Y-%m-%d)
d1=$(date -d "$exp" +%s)
d2=$(date -d "$now" +%s)

if [[ $d1 -ge $d2 ]]; then
    new_exp=$(date -d "$exp + $days days" +"%Y-%m-%d")
else
    new_exp=$(date -d "$days days" +"%Y-%m-%d")
fi

sed -i "s|// #hy $user $exp|// #hy $user $new_exp|g" "$CONFIG"
systemctl restart xray

clear
echo -e "${GREEN}Hysteria2 User ($user) Renewed Successfully!${NC}"
echo -e "Old Expiry: $exp  ->  New Expiry: $new_exp"
read -n 1 -s -r -p "Press any key to back on menu"
