#!/bin/bash
clear
CONFIG="/usr/local/etc/xray/config.json"
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${ORANGE}        RENEW SHADOWSOCKS ACCOUNT         ${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

if [[ $(grep -c "// #ss " "$CONFIG") == '0' ]]; then
    echo -e "${RED}Error: No Shadowsocks clients found!${NC}"
    read -n 1 -s -r -p "Press any key to back on menu"
    menu-ss.sh
    exit 1
fi

echo -e " ${GREEN}[0]  Cancel & Return to Menu${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e " NO   USER          EXPIRES"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
grep -E "// #ss " "$CONFIG" | awk '{print $3, $4}' | sort | uniq | awk '{printf " %-4s %-13s %-10s\n", NR".", $1, $2}'
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

read -p " Select Number : " num

# SAFETY CATCH: Trapdoor Exit
if [[ "$num" == "0" ]]; then menu-ss.sh; exit 0; fi
if ! [[ "$num" =~ ^[0-9]+$ ]]; then echo -e "${RED}Invalid input! Numbers only.${NC}"; sleep 1; renew-ss; exit 1; fi

user=$(grep -E "// #ss " "$CONFIG" | awk '{print $3}' | sort | uniq | sed -n "${num}p")
exp=$(grep -E "// #ss " "$CONFIG" | grep "$user" | awk '{print $4}' | head -n 1)

if [[ -z "$user" ]]; then
    echo -e "${RED}Error: Invalid selection.${NC}"
    sleep 1
    renew-ss
    exit 1
fi

read -p " Add Days      : " days
[[ -z "$days" ]] && days=30

now=$(date +%Y-%m-%d)
d1=$(date -d "$exp" +%s)
d2=$(date -d "$now" +%s)

if [[ $d1 -ge $d2 ]]; then
    new_exp=$(date -d "$exp + $days days" +"%Y-%m-%d")
else
    new_exp=$(date -d "$days days" +"%Y-%m-%d")
fi

sed -i "s|// #ss $user $exp|// #ss $user $new_exp|g" "$CONFIG"
systemctl restart xray

clear
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${ORANGE}     SHADOWSOCKS USER RENEWED             ${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e " Username    : ${GREEN}${user}${NC}"
echo -e " Days Added  : ${GREEN}${days} Days${NC}"
echo -e " Old Expiry  : ${RED}${exp}${NC}"
echo -e " New Expiry  : ${GREEN}${new_exp}${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
read -n 1 -s -r -p "Press any key to back on menu"
menu-ss.sh
