#!/bin/bash
clear
CONFIG="/usr/local/etc/xray/config.json"
domain=$(cat /etc/xray/domain)
PBK=$(cat /etc/xray/reality_public)
SID=$(cat /etc/xray/reality_shortid)

RED='\033[0;31m'; NC='\033[0m'; GREEN='\033[0;32m'; ORANGE='\033[0;33m'; BLUE='\033[0;34m'

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${ORANGE}        GENERATE TRIAL REALITY            ${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

rand=$(cat /proc/sys/kernel/random/uuid | cut -c1-4)
user="TRIAL-$rand"
masaaktif=1
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
exp_display="24 Hours (Trial)"
limit=1
sni="www.microsoft.com"

uuid=$(cat /proc/sys/kernel/random/uuid)

sed -i "s|// #reality|,\\
          { \"id\": \"$uuid\", \"flow\": \"xtls-rprx-vision\", \"email\": \"$user\" }\\
          // #reality\\
          // #re $user $exp|g" $CONFIG

mkdir -p /etc/xray/limit/vless
echo "$limit" > /etc/xray/limit/vless/$user
systemctl restart xray

reality_link="vless://${uuid}@${domain}:443?security=reality&encryption=none&pbk=${PBK}&headerType=none&fp=chrome&type=tcp&flow=xtls-rprx-vision&sni=${sni}&sid=${SID}#${user}"

clear
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${ORANGE}        TRIAL REALITY CREATED             ${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e " Username    : ${GREEN}${user}${NC}"
echo -e " Expired On  : ${GREEN}${exp_display}${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${ORANGE} LINK REALITY:${NC}"
echo -e "${GREEN}${reality_link}${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
read -n 1 -s -r -p "Press any key to back on menu"
menu-reality.sh
